### ISSUE TITLE
Intro was removed from Executive Summary (JSON Source 3/20/18)

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/budget.boston.gov#272]
The newest JSON (3/20/18) removes the Intro component from the Executive Summary, see this diff in the source:

![executive_summary_diff](https://user-images.githubusercontent.com/5913244/37668800-b2ad8be0-2c3b-11e8-8bce-1fe01a9d0d44.png)

Formerly, this page looked like this (as seen on the current staging site):

![intro_stg](https://user-images.githubusercontent.com/5913244/37668831-c1eaab06-2c3b-11e8-9739-c59299ca938b.png)

The new JSON renders like this (currently on local build):

![new_json](https://user-images.githubusercontent.com/5913244/37668849-cf763740-2c3b-11e8-812a-377fb6cc0633.png)

@paulparisi - Do you have insight into why this component was removed?

**Comment by jimwilliamson-boston** [comment]
The Mayor's quote was probably never added to web version in BudgetSoft
editor.

On Mar 20, 2018 1:00 PM, "reillyzlab" <notifications@github.com> wrote:

Assigned #272 <https://github.com/CityOfBoston/budget.boston.gov/issues/272>
to @jimwilliamson-boston <https://github.com/jimwilliamson-boston>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CityOfBoston/budget.boston.gov/issues/272#event-1531457987>,
or mute the thread

**Comment by jimafisk** [comment]
This has been fixed with the latest JSON source.
