### ISSUE TITLE
3/22/18 JSON ALL ORG/Programs Not Displaying on Budget Dept Page

### ISSUE THREAD

**Issue by jimwilliamson-boston** [CityOfBoston/budget.boston.gov#277]
https://budget.digital-staging.boston.gov/operating-budget/cabinets/administration-and-finance/budget-management/
![image](https://user-images.githubusercontent.com/27301004/37828459-b4a7e61a-2e71-11e8-97b1-3208ff6f471a.png)

**Comment by jimafisk** [comment]
These blank rows are coming through because the JSON source has `null` values instead of program names. See: https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_source/fy18_adopted/json/_departments/administration-and-finance/budget-management.json#L46

@paulparisi can you take a look? Thanks!

**Comment by jimwilliamson-boston** [comment]
Jim Fisk & I just looked at detail 19 data generated via JSON and the numbers look good.  Still have the issue with Program/Org names not showing up.

**Comment by paulparisi** [comment]
I have found and fixed this issue. In the dept, div and org tables there are several fields for, for example, OrgName, OrgName1, OrgName2 - these are used for instances where we need to accommodate the inability to have duplicate names in Hyperion. So we keep the name used for linking in one field and the "display" name in another. We will need to solidify these and use the correct ones throughout. I think for now this could be closed.
